// Generated by CoffeeScript 1.10.0
var Response, exports;

Response = (function() {
  function Response() {
    this.error_message = null;
    this.error_code = null;
    this.status_code = null;
  }

  Response.prototype.success = function(status_code) {
    this.error_code = null;
    this.error_message = null;
    return this.status_code = status_code;
  };

  Response.prototype.error = function(status_code, message, code) {
    if (code == null) {
      code = null;
    }
    this.error_code = code;
    this.error_message = message;
    return this.status_code = status_code;
  };

  Response.prototype.is_success = function() {
    return (this.error_code === null) && (this.error_message === null);
  };

  return Response;

})();

module.exports = exports = Response;
